// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using backend.Models;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20260901130245_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("JobApplicationJobPosting", b =>
                {
                    b.Property<int>("ApplicationsID")
                        .HasColumnType("int");

                    b.Property<int>("PostingsID")
                        .HasColumnType("int");

                    b.HasKey("ApplicationsID", "PostingsID");

                    b.HasIndex("PostingsID");

                    b.ToTable("JobApplicationJobPosting");
                });

            modelBuilder.Entity("backend.Models.JobApplication", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("AppliedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("WorkerUserID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WorkerUserID");

                    b.ToTable("JobApplication");
                });

            modelBuilder.Entity("backend.Models.JobPosting", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CompanyUserID")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("ID");

                    b.HasIndex("CompanyUserID");

                    b.ToTable("JobPosting");
                });

            modelBuilder.Entity("backend.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("UserID"));

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("HashPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("RefreshTokenExpiraryTime")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("UserID");

                    b.ToTable("Users");

                    b.HasDiscriminator().HasValue("User");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("backend.Models.Company", b =>
                {
                    b.HasBaseType("backend.Models.User");

                    b.Property<string>("CompanyName")
                        .HasColumnType("longtext");

                    b.Property<string>("PIB")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Company");
                });

            modelBuilder.Entity("backend.Models.Worker", b =>
                {
                    b.HasBaseType("backend.Models.User");

                    b.Property<string>("FullName")
                        .HasColumnType("longtext");

                    b.Property<string>("JobTitle")
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("Worker");
                });

            modelBuilder.Entity("JobApplicationJobPosting", b =>
                {
                    b.HasOne("backend.Models.JobApplication", null)
                        .WithMany()
                        .HasForeignKey("ApplicationsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.JobPosting", null)
                        .WithMany()
                        .HasForeignKey("PostingsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("backend.Models.JobApplication", b =>
                {
                    b.HasOne("backend.Models.Worker", "Worker")
                        .WithMany("Applications")
                        .HasForeignKey("WorkerUserID");

                    b.Navigation("Worker");
                });

            modelBuilder.Entity("backend.Models.JobPosting", b =>
                {
                    b.HasOne("backend.Models.Company", "Company")
                        .WithMany("JobPostings")
                        .HasForeignKey("CompanyUserID");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("backend.Models.Company", b =>
                {
                    b.Navigation("JobPostings");
                });

            modelBuilder.Entity("backend.Models.Worker", b =>
                {
                    b.Navigation("Applications");
                });
#pragma warning restore 612, 618
        }
    }
}
